apiVersion: v1
kind: Service
metadata:
  name: businesscv-service
  labels:
    app: businesscv
spec:
  selector:
    app: businesscv
  type: NodePort
  ports:
   - port: 5051
     # nodePort: <31514>